// Root layout with global fonts and metadata.
import type { Metadata } from "next";
import { LocaleProvider } from "@/app/_components/locale-provider";
import { getRequestMessages } from "@/lib/i18n/server";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { locale, messages } = await getRequestMessages();

  return (
    <html id="root-html" lang={locale} data-theme="sage">
      <body id="root-body" className="antialiased">
        <LocaleProvider locale={locale} messages={messages}>{children}</LocaleProvider>
      </body>
    </html>
  );
}
